apiVersion: autostager.autostager.com/v1alpha1
kind: Autostager
metadata:
  labels:
    app.kubernetes.io/name: autostager
    app.kubernetes.io/instance: autostager-sample
    app.kubernetes.io/part-of: autostager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: autostager
  name: autostager-sample
spec:
  helmMode: false
  image: "synoti21/diareat:latest"
  namespace: "example"
  containerPort: 80
  replicas: 1
  ingressHost: "home.thisiswandol.com"
